CREATE TABLE Contatos (
	CodContato INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Telefone VARCHAR(20) NOT NULL,
	Operadora INT NOT NULL,
	DataRegistro DATETIME NOT NULL
)

CREATE TABLE Operadoras (
	CodOperadora INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
)
